version: '2.32.1'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis:/data
    networks:
      - fr2-network
  web: 
    build:
      context: ./
      target: builder
    ports: 
      - '8000:8000'
    depends_on:
      - redis
    networks:
      - fr2-network
  predictor_service: 
    restart: always
    build:
      context: predict-service
      target: builder
    depends_on:
      - redis
    networks:
      - fr2-network
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
    networks:
      - fr2-network
    ports:
      - 27017:27017
volumes
  mongo-data:
    driver: local
  redis:
    driver: local

networks:
  fr2-network:
    driver: bridge
